using System.Linq;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.MagicMirror;
using Content.Shared.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.MagicMirror;

[GenerateTypedNameReferences]
public sealed partial class MagicMirrorWindow : DefaultWindow
{
    // MMMMMMM
    public Action<(int slot, string id)>? OnHairSelected;
    public Action<(int slot, Marking marking)>? OnHairColorChanged;
    public Action<int>? OnHairSlotRemoved;
    public Action? OnHairSlotAdded;
    public Action<(int slot, string id)>? OnFacialHairSelected;
    public Action<(int slot, Marking marking)>? OnFacialHairColorChanged;
    public Action<int>? OnFacialHairSlotRemoved;
    public Action? OnFacialHairSlotAdded;

    public Action<string>? OnVoiceSelected;
    public Action<string>? OnVoicePreview;

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private List<TTSVoicePrototype> _voiceList = default!;
    private string? _currentVoice;
    private TimeSpan _previewCooldown = TimeSpan.FromSeconds(2);
    private TimeSpan _lastPreviewTime = TimeSpan.Zero;

    public MagicMirrorWindow()
    {
        RobustXamlLoader.Load(this);

        HairPicker.OnMarkingSelect += args => OnHairSelected!(args);
        HairPicker.OnColorChanged += args => OnHairColorChanged!(args);
        HairPicker.OnSlotRemove += args => OnHairSlotRemoved!(args);
        HairPicker.OnSlotAdd += delegate { OnHairSlotAdded!(); };

        FacialHairPicker.OnMarkingSelect += args => OnFacialHairSelected!(args);
        FacialHairPicker.OnColorChanged += args => OnFacialHairColorChanged!(args);
        FacialHairPicker.OnSlotRemove += args => OnFacialHairSlotRemoved!(args);
        FacialHairPicker.OnSlotAdd += delegate { OnFacialHairSlotAdded!(); };

        IoCManager.InjectDependencies(this);

        _voiceList = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.CanSelect)
            .OrderBy(o => o.Sex)
            .ThenBy(o => Loc.GetString(o.Name))
            .ToList();

        VoiceButton.OnItemSelected += args =>
        {
            if (args.Id < 0)
            {
                // Reselect current voice if header is clicked
                var currentVoiceId = _voiceList.FindIndex(x => x.ID == _currentVoice);
                VoiceButton.SelectId(currentVoiceId);
                return;
            }

            VoiceButton.SelectId(args.Id);
            OnVoiceSelected?.Invoke(_voiceList[args.Id].ID);
        };

        VoicePlayButton.OnPressed += _ =>
        {
            if (_currentVoice == null)
                return;

            var currentTime = _timing.CurTime;
            if (currentTime - _lastPreviewTime < _previewCooldown)
                return;

            _lastPreviewTime = currentTime;
            OnVoicePreview?.Invoke(_currentVoice);
        };

        UpdateTTSVoicesControls();
    }

    private void UpdateTTSVoicesControls()
    {
        VoiceButton.Clear();

        Sex? lastSex = null;
        for (var i = 0; i < _voiceList.Count; i++)
        {
            var voice = _voiceList[i];

            if (lastSex != voice.Sex)
            {
                var categoryLoc = voice.Sex switch
                {
                    Sex.Male => "humanoid-profile-editor-voice-category-masculine",
                    Sex.Female => "humanoid-profile-editor-voice-category-feminine",
                    _ => "humanoid-profile-editor-voice-category-unsexed"
                };

                // Use unique negative IDs for headers and disable them
                var headerId = -(int)voice.Sex - 1;
                VoiceButton.AddItem(Loc.GetString(categoryLoc), headerId);
                VoiceButton.SetItemDisabled(VoiceButton.ItemCount - 1, true);

                lastSex = voice.Sex;
            }

            var name = Loc.GetString(voice.Name);
            VoiceButton.AddItem(name, i);
        }
    }

    public void UpdateState(MagicMirrorUiState state, bool isTarget)
    {
        HairPicker.UpdateData(state.Hair, state.Species, state.HairSlotTotal);
        FacialHairPicker.UpdateData(state.FacialHair, state.Species, state.FacialHairSlotTotal);

        _currentVoice = state.Voice;
        var voiceChoiceId = _voiceList.FindIndex(x => x.ID == state.Voice);
        VoiceButton.TrySelectId(voiceChoiceId);

        VoiceContainer.Visible = isTarget;

        var noOptions = !HairPicker.Visible && !FacialHairPicker.Visible && !VoiceContainer.Visible;
        NoOptionsLabel.Visible = noOptions;
    }
}
